-- ******************** SqlDBM: Microsoft SQL Server ********************
-- ************************* Generated by SqlDBM ************************


CREATE SEQUENCE Sequence_1 MAXVALUE 5 NOMINVALUE CYCLE NOORDER;