-- ****************************************************************************
-- * Generated by SqlDBM: Oracle test, v2 by alexey.alferov+oracle@sqldbm.com *


CREATE SCHEMA AUTHORIZATION Schema_1
-- ************************************** Schema_1.table_1
CREATE TABLE Schema_1.table_1
(
 col_2   INT INVISIBLE NOT NULL DEFAULT w5w534,
 col_1   BINARY FLOAT VISIBLE NOT NULL,
 CONSTRAINT PK_1 PRIMARY KEY (col_2, col_1)
);


-- ************************************** PostScript
trghtrt
-- ************************************** PostScript End Schema_1.table_1

CREATE SEQUENCE Sequence_1 MAXVALUE 5 NOMINVALUE CYCLE NOORDER;
