-- ******************** SqlDBM: Microsoft SQL Server ********************
-- ************************* Generated by SqlDBM ************************


-- ************************************** [dbo].[OrderItem]
CREATE TABLE [dbo].[OrderItem]
(
 [OrderId]   int NOT NULL ,
 [ProductId] int NOT NULL ,
 [UnitPrice] decimal(12,2) NOT NULL ,
 [Quantity]  int NOT NULL ,


 CONSTRAINT [PK_OrderItem] PRIMARY KEY CLUSTERED ([OrderId] ASC, [ProductId] ASC),
 CONSTRAINT [FK_OrderItem_OrderId_Order] FOREIGN KEY ([OrderId])  REFERENCES [dbo].[Order]([OrderId]),
 CONSTRAINT [FK_OrderItem_ProductId_Product] FOREIGN KEY ([ProductId])  REFERENCES [dbo].[Product]([ProductId])
);
GO


CREATE NONCLUSTERED INDEX [FK_OrderItem_OrderId_Order] ON [dbo].[OrderItem] 
 (
  [OrderId] ASC
 )

GO

CREATE NONCLUSTERED INDEX [FK_OrderItem_ProductId_Product] ON [dbo].[OrderItem] 
 (
  [ProductId] ASC
 )

GO


EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Information about
like Price, Quantity', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'OrderItem';
GO