-- ******************** SqlDBM: Microsoft SQL Server ********************
-- ************************* Generated by SqlDBM ************************


-- ************************************** [dbo].[Order]
CREATE TABLE [dbo].[Order]
(
 [OrderId]     int IDENTITY (1, 1) NOT NULL ,
 [OrderNumber] nvarchar(10) NULL ,
 [CustomerId]  int NOT NULL ,
 [OrderDate]   datetime NOT NULL CONSTRAINT [DF_Order_OrderDate] DEFAULT (getdate()) ,
 [TotalAmount] decimal(12,2) NOT NULL ,


 CONSTRAINT [PK_Order] PRIMARY KEY CLUSTERED ([OrderId] ASC),
 CONSTRAINT [AK1_Order_OrderNumber] UNIQUE NONCLUSTERED ([OrderNumber] ASC),
 CONSTRAINT [FK_Order_CustomerId_Customer] FOREIGN KEY ([CustomerId])  REFERENCES [dbo].[Customer]([CustomerId])
);
GO


CREATE NONCLUSTERED INDEX [FK_Order_CustomerId_Customer] ON [dbo].[Order] 
 (
  [CustomerId] ASC
 )

GO


EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Order information
like Date, Amount', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'Order';
GO